// const binarysearch = require('./src/BinarySearch');
// const selectionSort = require('./src/SelectionSort');
// const sum = require('./src/recursion');
// require('./src/QuickSort');
require('./src/playground');
// require('./src/Codility/arrays/CyclicRotation');
// require('./src/Codility/arrays/OddOccurrencesInArray');
// require('./src/Codility/Time Complexity/PermMissingElement');
// require('./src/Codility/Time Complexity/TapeEquilibrium');
require('./src/Codility/counting_elements/PermCheck');
